/**
 * Created by chang_su on 2017/6/19.
 */
export default {
    charCodes: [
        "\/::\\)", "\/::~", "\/::B", "\/::\\|", "\/:8-\\)", "\/::<", "\/::\\$", "\/::X", "\/::Z", "\/::'\\(", "\/::-\\|", "\/::@", "\/::P", "\/::D", "\/::O", "\/::\\(", "\/::\\+", "\/:--b", "\/::Q", "\/::T", "\/:,P", "\/:,-D", "\/::d", "\/:,o", "\/::g", "\/:\\|-\\)", "\/::!", "\/::L", "\/::>", "\/::,", "\/:,f", "\/::-S", "\/:\\?", "\/:,x", "\/:,@", "\/::8", "\/:,!", "\/:!!!", "\/:xx", "\/:bye", "\/:wipe", "\/:dig", "\/:handclap", "\/:&-\\(", "\/:B-\\)", "\/:<@", "\/:@>", "\/::-O", "\/:>-\\|", "\/:P-\\(", "\/::'\\|", "\/:X-\\)", "\/::\\*", "\/:@x", "\/:8\\*", "\/:pd", "\/:<W>", "\/:beer", "\/:basketb", "\/:oo", "\/:coffee", "\/:eat", "\/:pig", "\/:rose", "\/:fade", "\/:showlove", "\/:heart", "\/:break", "\/:cake", "\/:li", "\/:bome", "\/:kn", "\/:footb", "\/:ladybug", "\/:shit", "\/:moon", "\/:sun", "\/:gift", "\/:hug", "\/:strong", "\/:weak", "\/:share", "\/:v", "\/:@\\)", "\/:jj", "\/:@@", "\/:bad", "\/:lvu", "\/:no", "\/:ok", "\/:love", "\/:<L>", "\/:jump", "\/:shake", "\/:<O>", "\/:circle", "\/:kotow", "\/:turn", "\/:skip", "\/:oY", "\/:#-0", "\/:hiphot", "\/:kiss", "\/:<&", "\/:&>"
    ],
    chineseCodes: [
        "[微笑]", "[撇嘴]", "[色]", "[发呆]", "[得意]", "[流泪]", "[害羞]", "[闭嘴]", "[睡]", "[大哭]", "[尴尬]", "[发怒]", "[调皮]", "[呲牙]", "[惊讶]", "[难过]", "[酷]", "[囧]", "[抓狂]", "[吐]", "[偷笑]", "[愉快]", "[白眼]", "[傲慢]", "[饥饿]", "[困]", "[惊恐]", "[流汗]", "[憨笑]", "[悠闲]", "[奋斗]", "[咒骂]", "[疑问]", "[嘘]", "[晕]", "[折磨]", "[衰]", "[骷髅]", "[敲打]", "[再见]", "[擦汗]", "[抠鼻]", "[鼓掌]", "[溴大了]", "[坏笑]", "[左哼哼]", "[右哼哼]", "[哈欠]", "[鄙视]", "[委屈]", "[快哭了]", "[阴险]", "[亲亲]", "[吓]", "[可怜]", "[菜刀]", "[西瓜]", "[啤酒]", "[篮球]", "[乒乓]", "[咖啡]", "[饭]", "[猪头]", "[玫瑰]", "[凋谢]", "[嘴唇]", "[爱心]", "[心碎]", "[蛋糕]", "[闪电]", "[炸弹]", "[刀]", "[足球]", "[瓢虫]", "[便便]", "[月亮]", "[太阳]", "[礼物]", "[拥抱]", "[强]", "[弱]", "[握手]", "[胜利]", "[抱拳]", "[勾引]", "[拳头]", "[差劲]", "[爱你]", "[NO]", "[OK]", "[爱情]", "[飞吻]", "[跳跳]", "[发抖]", "[怄火]", "[转圈]", "[磕头]", "[回头]", "[跳绳]", "[挥手]", "[激动]", "[街舞 ]", "[献吻]", "[左太极]", "[右太极]"
    ],
    fullChineseCodes: [
        "\\[微笑\\]", "\\[撇嘴\\]", "\\[色\\]", "\\[发呆\\]", "\\[得意\\]", "\\[流泪\\]", "\\[害羞\\]", "\\[闭嘴\\]", "\\[睡\\]", "\\[大哭\\]", "\\[尴尬\\]", "\\[发怒\\]", "\\[调皮\\]", "\\[呲牙\\]", "\\[惊讶\\]", "\\[难过\\]", "\\[酷\\]", "\\[囧\\]", "\\[抓狂\\]", "\\[吐\\]", "\\[偷笑\\]", "\\[愉快\\]", "\\[白眼\\]", "\\[傲慢\\]", "\\[饥饿\\]", "\\[困\\]", "\\[惊恐\\]", "\\[流汗\\]", "\\[憨笑\\]", "\\[悠闲\\]", "\\[奋斗\\]", "\\[咒骂\\]", "\\[疑问\\]", "\\[嘘\\]", "\\[晕\\]", "\\[折磨\\]", "\\[衰\\]", "\\[骷髅\\]", "\\[敲打\\]", "\\[再见\\]", "\\[擦汗\\]", "\\[抠鼻\\]", "\\[鼓掌\\]", "\\[溴大了\\]", "\\[坏笑\\]", "\\[左哼哼\\]", "\\[右哼哼\\]", "\\[哈欠\\]", "\\[鄙视\\]", "\\[委屈\\]", "\\[快哭了\\]", "\\[阴险\\]", "\\[亲亲\\]", "\\[吓\\]", "\\[可怜\\]", "\\[菜刀\\]", "\\[西瓜\\]", "\\[啤酒\\]", "\\[篮球\\]", "\\[乒乓\\]", "\\[咖啡\\]", "\\[饭\\]", "\\[猪头\\]", "\\[玫瑰\\]", "\\[凋谢\\]", "\\[嘴唇\\]", "\\[爱心\\]", "\\[心碎\\]", "\\[蛋糕\\]", "\\[闪电\\]", "\\[炸弹\\]", "\\[刀\\]", "\\[足球\\]", "\\[瓢虫\\]", "\\[便便\\]", "\\[月亮\\]", "\\[太阳\\]", "\\[礼物\\]", "\\[拥抱\\]", "\\[强\\]", "\\[弱\\]", "\\[握手\\]", "\\[胜利\\]", "\\[抱拳\\]", "\\[勾引\\]", "\\[拳头\\]", "\\[差劲\\]", "\\[爱你\\]", "\\[NO\\]", "\\[OK\\]", "\\[爱情\\]", "\\[飞吻\\]", "\\[跳跳\\]", "\\[发抖\\]", "\\[怄火\\]", "\\[转圈\\]", "\\[磕头\\]", "\\[回头\\]", "\\[跳绳\\]", "\\[挥手\\]", "\\[激动\\]", "\\[街舞 \\]", "\\[献吻\\]", "\\[左太极\\]", "\\[右太极\\]", "\\[奸笑\\]", "\\[嘿哈\\]", "\\[捂脸\\]", "\\[机智\\]", "\\[茶\\]", "\\[红包\\]", "\\[蜡烛\\]", "\\[耶\\]", "\\[皱眉\\]"
    ],
    images: [
        "Expression_1.png", "Expression_2.png", "Expression_3.png", "Expression_4.png", "Expression_5.png", "Expression_6.png", "Expression_7.png", "Expression_8.png", "Expression_9.png", "Expression_10.png", "Expression_11.png", "Expression_12.png", "Expression_13.png", "Expression_14.png", "Expression_15.png", "Expression_16.png", "Expression_17.png", "Expression_18.png", "Expression_19.png", "Expression_20.png", "Expression_21.png", "Expression_22.png", "Expression_23.png", "Expression_24.png", "Expression_25.png", "Expression_26.png", "Expression_27.png", "Expression_28.png", "Expression_29.png", "Expression_30.png", "Expression_31.png", "Expression_32.png", "Expression_33.png", "Expression_34.png", "Expression_35.png", "Expression_36.png", "Expression_37.png", "Expression_38.png", "Expression_39.png", "Expression_40.png", "Expression_41.png", "Expression_42.png", "Expression_43.png", "Expression_44.png", "Expression_45.png", "Expression_46.png", "Expression_47.png", "Expression_48.png", "Expression_49.png", "Expression_50.png", "Expression_51.png", "Expression_52.png", "Expression_53.png", "Expression_54.png", "Expression_55.png", "Expression_56.png", "Expression_57.png", "Expression_58.png", "Expression_59.png", "Expression_60.png", "Expression_61.png", "Expression_62.png", "Expression_63.png", "Expression_64.png", "Expression_65.png", "Expression_66.png", "Expression_67.png", "Expression_68.png", "Expression_69.png", "Expression_70.png", "Expression_71.png", "Expression_72.png", "Expression_73.png", "Expression_74.png", "Expression_75.png", "Expression_76.png", "Expression_77.png", "Expression_78.png", "Expression_79.png", "Expression_80.png", "Expression_81.png", "Expression_82.png", "Expression_83.png", "Expression_84.png", "Expression_85.png", "Expression_86.png", "Expression_87.png", "Expression_88.png", "Expression_89.png", "Expression_90.png", "Expression_91.png", "Expression_92.png", "Expression_93.png", "Expression_94.png", "Expression_95.png", "Expression_96.png", "Expression_97.png", "Expression_98.png", "Expression_99.png", "Expression_100.png", "Expression_101.png", "Expression_102.png", "Expression_103.png", "Expression_104.png", "Expression_105.png", "Expression_106.png", "Expression_107.png", "Expression_108.png", "Expression_109.png", "Expression_110.png", "Expression_111.png", "Expression_112.png", "Expression_113.png", "Expression_114.png"
    ]
}
